name: e2e

on:
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

jobs:
  stack:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        stack: [postgres, grafana]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - run: ./e2e/${{ matrix.stack }}/run.sh
